title: Yzec7的博客
email: ecgsqyyf@gmail.com
description: 杨至的博客。 # 这里是你网站的描述
baseurl: "" # 项目的基本路径，如果你的站点放在根目录下，则留空
url: "http://yzec7.github.io" # 网站的URL
github_username:  yzec7

# 构建设置
theme: minima # 使用的主题
plugins:
  - jekyll-feed # 示例插件
