title: Yzec7的博客
email: ecgsqyyf@gmail.com
description: 杨至的博客。 # 这里是你网站的描述
baseurl: "" # 项目的基本路径，如果你的站点放在根目录下，则留空
url: "http://yzec7.github.io" # 网站的URL
github_username:  yzec7

# 构建设置
markdown: kramdown         # Markdown 解析器
theme: minima              # 使用的 Jekyll 主题
plugins:
  - jekyll-feed            # 使用的插件，例如 jekyll-feed

# Jekyll 主题或插件的其他配置
minima:
  skin: dark               # 主题特定的配置，例如 Minima 主题的皮肤颜色

# 自定义构建目录（可选）
destination: ./_site       # Jekyll 构建网站的输出目录
